### ISSUE TITLE
Concept list to Concepticon before release?

### ISSUE THREAD

**Issue by chrzyki** [lexibank/daniellinguafrancas#7]
I'll have a look at the data in a bit; one small question before that: Having the concept list in Concepticon proper instead of in this repository would be nice. Have you talked about this before, @ilchec and @LinguList?

**Comment by LinguList** [comment]
Sorry to not answer to this earlier: the current procedure we have the best experience with is to have a release of the code, publish the paper, and then add the concepts to Concepticon, as this means that the paper is also there and not quoted as "forthcoming" and we have to update the information in Concepticon later (e.g., also changing the year in the ID of concepts). This worked so far okay with Gerardi-2021-414, although this is not the prime example, since in this dataset, the number of concepts in the paper differs from the actual number in the data, etc., but it would've been Gerardi-2020-404 first, and then Gerardi-2021-414, etc., so lots of changes.

**Comment by chrzyki** [comment]
No worries and thanks for the explanation! At the time of opening the issue, I wasn't aware that the paper is still to be published. Makes sense to wait then. :)

**Comment by LinguList** [comment]
Therefore we also have the different wording, since this paper 
supplemnets the CLDF directly, upon publication.
